FileVersion = 1

[Project]
Name = "flex-beef"
DefaultNamespace = "flex"

[Configs.Debug.Win64]
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\windows\\flexd.lib"]

[Configs.Debug.Win64]
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\windows\\flex.lib"]
