FileVersion = 1

[Project]
Name = "flex-beef"
DefaultNamespace = "flex"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\flex_d.lib"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\flex.lib"]
